### ISSUE TITLE
Review Issue

### ISSUE THREAD

**Issue by mmatongo** [mmatongo/group-capstone#21]
#### LINK TO REPO
- https://github.com/mmatongo/group-capstone/projects/2

#### TEAM MEMBERS
Our team has only two members, their GitHub accounts are linked below.

- [Daniel M. Matongo](https://github.com/mmatongo)
- [Oni Olajumoke Priscilla](https://github.com/prolajumokeoni)

**Comment by Davidosky007** [comment]
Hi @mmatongo @prolajumokeoni, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, with the wrong link, link should take me to the project 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mmatongo** [comment]
> Hi @mmatongo @prolajumokeoni,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, with the wrong link, link should take me to the project
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Apologies for that, it was a mistype.

**Comment by vichuge** [comment]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your PR messages are descriptive ✔️

## Aspects to improve ♻️

- [ ] Please, consider the next. For a team with 2 people, the number of cards on board should be equal to 15. At this point you've 20, please work on this.
![image](https://user-images.githubusercontent.com/20563252/132231178-70617cd8-30cf-46a3-b50b-8d8efab9c78b.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mmatongo** [comment]
> ## Aspects to improve ♻️
> * [ ]  Please, consider the next. For a team with 2 people, the number of cards on board should be equal to 15. At this point you've 20, please work on this.
>   ![image](https://user-images.githubusercontent.com/20563252/132231178-70617cd8-30cf-46a3-b50b-8d8efab9c78b.png)


Thank you.

**Comment by vichuge** [comment]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
